name: Publish RetroHue

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: codeberg-tiny

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: https://data.forgejo.org/actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Publish to Package Registry
        run: ./gradlew publish --no-daemon --info
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
